version: 2

models:
  - name: customer_details
    description: "This model contains customer details for the insurance company, built in the customer_analytics project."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "The full name of the customer."
      - name: customer_email
        description: "The email address of the customer."
