# dbt_project.yml for customer_analytics
name: 'customer_analytics'
version: '1.0.0'
config-version: 2

profile: my_dbt_projects
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  customer_analytics:
    example:
      +materialized: view
